[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = ["macros", "sqlite", "runtime-tokio"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
